apiVersion: sentinel.sre/v1
kind: Guard

metadata:
  name: checkout-api
  owner: payments-sre
  environment: dev

target:
  cluster: minikube
  namespace: default
  service: checkout

signals:
  traffic:
    source: prometheus
    query: sum(rate(demoapi_http_requests_total[1m]))
    minRPS: 0.1

  errors:
    source: prometheus
    query: demoapi_http_requests_total{status_class="5xx"}

  slo:
    objective: 99.9
    window: 30d

policy:
  budget:
    fastBurn:
      window: 5m
      threshold: 14
    slowBurn:
      window: 1h
      threshold: 2
    minRemaining: 10%

canary:
  enabled: false
